### ISSUE TITLE
`anonymized_telemetry: false` not working in profile and env

### ISSUE THREAD

**Issue by LucienShui** [OpenInterpreter/open-interpreter#1151]
### Describe the bug

When I'm trying to disable telemetery using the profile, I find that interpreter still calling the posthog.com.

### Reproduce

Here's my `profiles/default.yaml`.

```yaml
llm:
  model: "model"
  temperature: 0
  api_key: "***"
  api_base: "***"
  context_window: 2048
  llm_supports_functions: false
  llm.llm_supports_vision: false
anonymized_telemetry: false

version: 0.2.1
```

After that when I execute `interperter` in the terminal, I got error of request `posthog.com`. (Cause my AdGuardHome has banned it)

### Expected behavior

No telemetry.

### Screenshots

<img width="732" alt="image" src="https://github.com/OpenInterpreter/open-interpreter/assets/30151093/18edfde6-1283-4eaa-9aba-a1f6554baa0b">

### Open Interpreter version

0.2.4

### Python version

3.10.14

### Operating System name and version

macOS 14.3.1

### Additional context

`interpreter --disable_telemetry` worked.
