### ISSUE TITLE
DeepSeek Integration: Improving Minor Details

### ISSUE THREAD

**Issue by webia1** [OpenInterpreter/open-interpreter#1314]
### Is your feature request related to a problem? Please describe.

Yes, I can create a profile for DeepSeeker, and everything works well overall. However, when reading the files, it encounters problems. It seems there's a minor issue; it finds the files but cannot read them.

### Describe the solution you'd like

For example, this is a profile `deepseeker.yaml` I use for DeepSeeker, and perhaps a key like "no fear, you can read files" would be useful for DeepSeeker. DeepSeeker is extremely shy.

```yaml
llm:
  model: "deepseek-coder"
  temperature: 0
  api_key: "sk-..." 
  api_base: "https://api.deepseek.com/v1" 
  max_output: 2500 

computer:
  import_computer_api: True 
  emit_images: True
  verbose: True

auto_run: True 
safe_mode: "ask" 
multi_line: True 
version: 0.2.5 
```

### Describe alternatives you've considered

I have tried almost every option listed here: [OpenInterpreter Settings](https://docs.openinterpreter.com/settings). Perhaps DeepSeeker needs to be taught differently to be less shy.

### Additional context

The "deepseek-coder" model works extremely well compared to the competition.
