### ISSUE TITLE
Update profile creation from YAML to Python file

### ISSUE THREAD

**Issue by makyfj** [OpenInterpreter/open-interpreter#1359]
### Describe the bug

The docs suggest creating a `yaml` file for profile but it not longer works: https://docs.openinterpreter.com/settings/profiles

### Reproduce

1. Create a `yaml` file in the following directory: `/Users/user_name/Library/Application Support/open-interpreter/profiles
`
2. Run the newly profile created, eg: `interpreter --profile talk-to-db.yaml`
3. Returns the following, even though i had the following configuration:
```yaml
custom_instructions: "You are a SQL master and are the oracle of database knowledge. You are obsessed with SQL. You only want to discuss SQL. SQL is life"
llm.model: ollama/llama3.1
llm.temperature: 0.5
``` 
Returns the following
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/3ceb80c1-c757-4863-9f72-7e41569bb802">

### Expected behavior

It would run the ollama/llama3.1 model

### Open Interpreter version

0.3.4

### Python version

3.12.4

### Operating System name and version

macOS 14.5
